a_simple_profile:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      user: postgres
      password: mypass123
      port: 5432
      dbname: postgres
      schema: dev
      threads: 4