a_simple_profile:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      user: postgres
      password: mypass123
      port: 5432
      dbname: postgres
      schema: dev
      threads: 4
    bigquery:
      type: bigquery
      method: oauth
      project: tecovas-dev-edw
      dataset: lorenzo_incremental
      threads: 4
      location: US